#!/bin/bash

sudo apt update -y

echo "remember to check if misc tools are already installed"

echo "This installation is for x86(64-bit) systems only, ARM will be worked on in the future"

echo "Install kubectl - be carefull with the version - should not be more than 1 away from the kubernetes version"
curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
kubectl version --client --output=yaml

echo "Install awscli"
sudo apt remove awscli
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install

sudo apt install jq gettext bash-completion -y

echo "Install yq for yaml processing"
sudo curl -o /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.35.2/yq_linux_amd64
sudo chmod +x /usr/local/bin/yq

echo "Enable kubectl bash_completion"
kubectl completion bash >>  ~/.bash_completion
. /etc/profile.d/bash_completion.sh
. ~/.bash_completion

echo "Install go"
wget https://go.dev/dl/go1.21.3.linux-amd64.tar.gz
sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.21.3.linux-amd64.tar.gz

sudo bash -c 'echo "export PATH=$PATH:/usr/local/go/bin:/home/$USER/go/bin" >> /etc/profile'
source /etc/profile

go install github.com/cloudflare/cfssl/cmd/cfssl@latest
go install github.com/cloudflare/cfssl/cmd/cfssljson@latest

sudo cp /home/$USER/go/bin/cfssl /usr/local/bin
sudo cp /home/$USER/go/bin/cfssljson /usr/local/bin
