#!/bin/bash

kubectl apply -f coredns-1.9.4.yaml

sleep 2

kubectl get pods -l k8s-app=kube-dns -n kube-system

kubectl run busybox --image=busybox:1.28 --command -- sleep 3600

POD_NAME=$(kubectl get pods -l run=busybox -o jsonpath="{.items[0].metadata.name}")

kubectl exec -ti "$POD_NAME" -- nslookup kubernetes

