#!/bin/bash -x

for controller in 1 2 3; do
  echo "Updating ${controller}"
  external_ip=$(aws ec2 describe-instances \
    --filters "Name=tag:Name,Values=controller-${controller}" "Name=instance-state-name,Values=running" \
    --output text --query 'Reservations[].Instances[].PublicIpAddress')

  < bootstrap-etcd-cluster ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
    -i kubernetes-the-hard-way.id_rsa ubuntu@"${external_ip}"
done
