#!/bin/bash

for controller in 1 2 3; do
  echo "Updating ${controller}"
  external_ip=$(aws ec2 describe-instances \
    --filters "Name=tag:Name,Values=controller-${controller}" "Name=instance-state-name,Values=running" \
    --output text --query 'Reservations[].Instances[].PublicIpAddress')

  ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
    -i kubernetes-the-hard-way.id_rsa ubuntu@"${external_ip}"

  echo "Download and Install the etcd Binaries"
  wget -q --show-progress --https-only --timestamping \
    "https://github.com/etcd-io/etcd/releases/download/v3.5.6/etcd-v3.5.6-linux-amd64.tar.gz"

  {
    tar -xvf etcd-v3.5.6-linux-amd64.tar.gz
    sudo mv etcd-v3.5.6-linux-amd64/etcd* /usr/local/bin/
  }

  echo "Configure the etcd Server"
  {
    sudo mkdir -p /etc/etcd /var/lib/etcd
    sudo chmod 700 /var/lib/etcd
    sudo cp ca.pem kubernetes-key.pem kubernetes.pem /etc/etcd/
  }

  INTERNAL_IP=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)
  echo "${INTERNAL_IP}"

  ETCD_NAME=$(curl -s http://169.254.169.254/latest/user-data/ |
    tr "|" "\n" | grep "^name" | cut -d"=" -f2)
  echo "${ETCD_NAME}"

  cat <<EOF | sudo tee /etc/systemd/system/etcd.service
[Unit]
Description=etcd
Documentation=https://github.com/coreos

[Service]
Type=notify
ExecStart=/usr/local/bin/etcd \\
  --name ${ETCD_NAME} \\
  --cert-file=/etc/etcd/kubernetes.pem \\
  --key-file=/etc/etcd/kubernetes-key.pem \\
  --peer-cert-file=/etc/etcd/kubernetes.pem \\
  --peer-key-file=/etc/etcd/kubernetes-key.pem \\
  --trusted-ca-file=/etc/etcd/ca.pem \\
  --peer-trusted-ca-file=/etc/etcd/ca.pem \\
  --peer-client-cert-auth \\
  --client-cert-auth \\
  --initial-advertise-peer-urls https://${INTERNAL_IP}:2380 \\
  --listen-peer-urls https://${INTERNAL_IP}:2380 \\
  --listen-client-urls https://${INTERNAL_IP}:2379,https://127.0.0.1:2379 \\
  --advertise-client-urls https://${INTERNAL_IP}:2379 \\
  --initial-cluster-token etcd-cluster-0 \\
  --initial-cluster controller-0=https://10.240.0.10:2380,controller-1=https://10.240.0.11:2380,controller-2=https://10.240.0.12:2380 \\
  --initial-cluster-state new \\
  --data-dir=/var/lib/etcd
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

  echo "Start the etcd Server"
  {
    sudo systemctl daemon-reload
    sudo systemctl enable etcd
    sudo systemctl start etcd
  }

done

echo "Verification"
sudo ETCDCTL_API=3 etcdctl member list \
  --endpoints=https://127.0.0.1:2379 \
  --cacert=/etc/etcd/ca.pem \
  --cert=/etc/etcd/kubernetes.pem \
  --key=/etc/etcd/kubernetes-key.pem